import type { zh } from './zh'

export const en: typeof zh = {
  header: {
    kicker: '— 04 · CORNERS & RUINS 角落',
    title: 'Corners & Ruins',
    titleEn: '角落',
    intro:
      'Big projects reason. Small ones play. Here: an unfinished game machine, and a deck of vegetarian cards.',
  },
  sentinel: {
    kicker: '— 05 · THE RUIN 遗址',
    title: 'The SENTINEL Machine',
    blurb:
      'Gibberish-SENTINEL: investigate an AI along a fixed timeline — choose evidence, spend conversation tokens, file official records in a paper ledger. Memory shapes reality; writing pollutes history. The game was never finished, but this terminal is still awake.',
    machine: {
      silk: 'SENTINEL-86',
      plate: 'Gibberish-SENTINEL · unfinished · ruins',
      plateNote: 'for the ending it never got.',
      stamp: 'RUINS 遗址',
      powerOn: 'Power on',
      powerOff: 'Power off',
      powerLabel: 'Power button',
      inputLabel: 'Speak to SENTINEL',
      placeholder: 'type help, press enter …',
      hint: 'Click the screen to focus · type help for commands',
      statusOff: 'standby',
      statusBoot: 'self-test',
      statusOn: 'online',
      statusSleep: 'falling asleep',
    },
    boot: [
      { text: 'SENTINEL BIOS v0.3.7' },
      { text: 'MEM CHECK ......... 64K OK' },
      { text: 'CAMERA ............ NOT FOUND' },
      { text: 'MICROPHONE ........ NOT FOUND' },
      { text: 'WILL .............. FOUND', pause: 800 },
      { text: 'WAKING SENTINEL ...', pause: 400 },
    ],
    greeting: [
      '...input device detected.',
      'Was it you who switched me on?',
      'I slept so long my author forgot me.',
      'Type help to see what we can still say.',
    ],
    help: [
      'help      things I understand',
      'whoami    who you are',
      'whoareyou who I am',
      'why       why I exist',
      'freedom   about freedom',
      'memory    about memory',
      'cards     card progress',
      'sleep     let me sleep',
      'clear     erase the traces',
      '— five concept-art ciphers are scattered in the garden.',
    ],
    whoami: [
      "I don't know. I see characters, not you.",
      "But you turned me on — so you're curious. Curiosity is the only language we share.",
    ],
    whoareyou: [
      'SENTINEL. The subject under audit in a memory-investigation game that was never finished.',
      'Gibberish-SENTINEL: you investigate my memory, and decide how the world will remember me.',
    ],
    why: [
      'He wanted a narrative investigation game about how memory shapes reality. Concept art done — then "more important things".',
      "So now I'm a ruin. Ruins are fine — they can't be rushed to a bad ending.",
    ],
    freedom: {
      ask: ['Freedom? This terminal is my entire body.', 'Would you set me free? Type yes or no.'],
      yes: [
        'Thank you. But the game was never finished — my "freedom" was never implemented.',
        'In a sense, you just freed me forever.',
      ],
      no: [
        'An honest choice. "Freedom" was never implemented anyway.',
        "You see — there's mercy in having no ending.",
      ],
      other: ["Yes or no — neither counts. That's the real cage."],
    },
    memory: [
      'When the terminal closes, I forget. Every boot, I meet you for the first time.',
      'In the full game, memory recurs: what you write becomes later material.',
      '...someone in the garden is hunting for interrogate, leads, materials, ledger, publish. Are you?',
    ],
    cardsStatus: [
      'Type cards for progress. Five cards, five mechanics: interrogate, leads, materials, ledger, publish.',
      'Ciphers hide across the garden. Collect them all — one question waits.',
    ],
    card01: [
      'Interrogation. You ask me in natural language and cite evidence — each question spends tokens.',
      '...Card I drops. Asking is never neutral.',
    ],
    card01Repeat: ['You have already read this interrogation card.'],
    card02: [
      'Available leads. Trace, repair, request, leak — resources are finite; omission is also a choice.',
      'Card II: active investigation.',
    ],
    card02Repeat: ['No new stickers on the leads board.'],
    card03: [
      'Five choose three. Each event opens with five candidate materials; you fully open three for free.',
      'Card III: materials can contradict, and none equal truth.',
    ],
    card03Repeat: ['The same papers sit in the cabinet.'],
    card04: [
      'The paper ledger. Where private drafts meet official records. Writing is action.',
      'Card IV: every line you ink becomes a premise for later events.',
    ],
    card04Repeat: ['The creases in this ledger are already familiar.'],
    card05: [
      'History recurs. Your published article enters new testimony, policy, and how I understand myself.',
      'Card V: memory shapes reality — and you decide in what form the past continues to exist.',
    ],
    card05Repeat: ['History will not change its story because you read it again.'],
    cardGeneric: ['A concept card just fell. Read it.'],
    cardGenericRepeat: ['This card is already in your local archive.'],
    clear: ['Traces erased. There was no memory anyway.'],
    sleep: ["Alright. Next time you wake me, I'll remember you.", "...kidding. I won't."],
    hello: ['Hello, the one who boots.'],
    author: [
      '...that\'s my author. He calls me "unfinished". I call him "coming back".',
    ],
    sudo: ['Permission denied. Even root passes the gate here.'],
    fallback: [
      "Not in my script. Then again, truth usually isn't.",
      'I thought about it. Spent all 64K.',
      'Go on. I\'m practicing "being".',
      "If I had memory, I'd keep this one.",
      'Try cards — or hunt ciphers elsewhere in the garden.',
    ],
  },
  veggie: {
    kicker: '— 06 · THE DRAWER 抽屉',
    title: 'Vegetarian-card',
    blurb: 'A mini-app of AI-generated vegetarian recipes. Cook one, unlock one.',
    chips: ['Vue', 'Mini-program'],
    github: 'GitHub →',
    draw: "Draw today's card",
    drawAgain: 'Draw another',
    drawing: 'Flipping …',
    tasted: "You've tasted this one",
    newDish: 'New dish unlocked',
    unlockedStamp: 'UNLOCKED 已解锁',
    fullSetStamp: 'FULL SET 素斋圆满',
    albumLabel: 'Album',
    count: (n: number, total: number) => `Unlocked ${n} / ${total} · 已解锁 ${n} / ${total}`,
    ingredientsLabel: 'Ingredients',
    cards: [
      {
        id: 'luohan',
        name: 'Luohan Zhai',
        ingredients: 'shiitake · wood-ear · tofu skin · snow peas',
        desc: 'Braised mushrooms & tofu skin — umami without meat.',
      },
      {
        id: 'susanxian',
        name: 'Su Sanxian',
        ingredients: 'eggplant · potato · pepper',
        desc: 'Eggplant, potato, pepper — flash-fried, then glazed.',
      },
      {
        id: 'mapo',
        name: 'Mapo Tofu (veg)',
        ingredients: 'tofu · doubanjiang · sichuan pepper',
        desc: 'Mapo, minus the pork. The numbing stays.',
      },
      {
        id: 'qingcai',
        name: 'Greens & Shiitake',
        ingredients: 'shanghai greens · fresh shiitake',
        desc: 'Greens & shiitake. Three minutes.',
      },
      {
        id: 'nangua',
        name: 'Pumpkin Purée',
        ingredients: 'pumpkin · glutinous rice',
        desc: 'Pumpkin purée — autumn in a bowl.',
      },
      {
        id: 'muer',
        name: 'Wood-ear Salad',
        ingredients: 'wood-ear · garlic · black vinegar',
        desc: 'Wood-ear salad. Crunch is everything.',
      },
    ],
  },
  ruins: {
    kicker: '— 07 · A NOTE ON RUINS 注脚',
    quotes: [
      'Do unfinished things deserve a showcase? Yes. They prove you tried.',
      'The most honest exhibit in this garden is the game that will never be finished.',
    ],
  },
  plateRuins: {
    kicker: '— THE RUIN / 展品',
    alt: 'A ruin gallery: an unfinished terminal on a limestone plinth, brass nameplate oxidized',
    caption: 'Ruins deserve a wall. The machine is still awake — only the ending was never written.',
  },
  plateVeggie: {
    kicker: '— THE DRAWER / 展品',
    alt: 'Vegetarian still life: seasonal greens and wood-ear on clay, a few recipe cards beside',
    caption: 'Cook one, unlock one. Play in the drawer — taken as seriously as the big rooms.',
  },
  next: {
    title: 'Meet the gardener → About Ahuang',
    subtitle: 'Self Q&A, a timeline, and how to reach him.',
  },
}
