import type { Lang } from '@/context/LangContext'

/**
 * Do-SOUL-Alaya 页面文案 · Bilingual copy for the /alaya page.
 * Page-scoped module (shared src/content.ts is owned by the scaffold).
 * Components read `alayaContent[lang]` via `useLang()`.
 */
const zh = {
  hero: {
    kicker: '— 贰 · 记忆 MEMORY · DO-SOUL-ALAYA',
    title: 'Do-SOUL-Alaya',
    subtitle: 'CLI 编码 Agent 的本地优先记忆层',
    slogan: 'The local-first memory plane for CLI coding agents.',
    chips: ['v0.3.11', 'MIT', 'TypeScript', 'SQLite · WAL', 'MCP stdio', 'Node ≥20.19', 'pnpm ≥9'],
    ctaGithub: 'GitHub 仓库 →',
    ctaDemo: '看记忆怎么活 ↓',
    vertical: '终端一关，它就忘了',
  },
  itch: {
    kicker: '— 痛点 THE ITCH',
    termPrompt: '$ exit',
    termC1: '# 终端关闭',
    termC2: '# 会话结束。它全忘了。',
    big: '向量数据库回答的是「什么字符串相似」，不是「什么是真的」。',
    core: 'Similarity is not truth.',
  },
  grammar: {
    kicker: '— 设计语法 THE GRAMMAR · 三层 × 四轴',
    title: '三层 × 四轴，每张牌只有一个家',
    layers: [
      { en: 'Memory Ontology', zh: '记忆本体' },
      { en: 'Structure Registry', zh: '结构注册' },
      { en: 'Runtime Control', zh: '运行时控制' },
    ],
    axes: [
      { en: 'Object', zh: '对象' },
      { en: 'Path', zh: '路径' },
      { en: 'Evidence', zh: '证据' },
      { en: 'Governance', zh: '治理' },
    ],
    cells: [
      [
        { label: '记忆对象', duty: '定义「一条记忆是什么」。' },
        { label: '本体寻址', duty: '记忆对象的标识与寻址。' },
        { label: '出处', duty: '每条记忆携带的证据与出处。' },
        { label: '状态机', duty: '候选 → 有效 → 驳回的状态流转。' },
      ],
      [
        { label: '结构对象', duty: '层级与关系的注册表。' },
        { label: '命名路径', duty: '结构的命名路径与归属。' },
        { label: '变更痕迹', duty: '结构变更的审计痕迹。' },
        { label: '结构提案', duty: '结构变更走提案，不直写。' },
      ],
      [
        { label: '运行时对象', duty: '会话、信号、回执。' },
        { label: '运行寻址', duty: 'EventLog 与队列的寻址。' },
        { label: '回执度量', duty: '回执与运行度量。' },
        { label: '闸门裁决', duty: 'soul.resolve 的六种裁决。' },
      ],
    ],
    invariant: '不变量：一个对象 / 索引 / 状态，只能在一个轴上作为真相源。',
    hint: '点按一格，看它属于哪根轴。',
  },
  lifecycle: {
    kicker: '— 试试 TRY IT · SIX STAGES, ONE GATE',
    title: '记忆生命周期',
    sub: '一条记忆要活过六关。点一点，或者让它自己流。',
    auto: '自动流转',
    stageLabel: '阶段',
    preventPrefix: '防 ✕',
    stages: [
      {
        name: '感知',
        en: 'Perception',
        line: '候选信号进入、分流；不触碰本体真相。',
        prevent: '「流利但错误」直接变成事实',
      },
      {
        name: '治理',
        en: 'Governance',
        line: '两条评审路径：inline soul.resolve（六种裁决），或 out-of-band Proposal。',
        prevent: '「agent said so」成为治理论据',
      },
      {
        name: '沉淀',
        en: 'Durability',
        line: 'EventLog append → DB mutation → notify。审计先于广播。',
        prevent: '先广播、后补账',
      },
      {
        name: '召回',
        en: 'Recall',
        line: '粗筛 → FTS → 精排；embedding 仅加权补充，永不覆盖。',
        prevent: '相似度拍板、顶替证据',
      },
      {
        name: '回执',
        en: 'Receipt',
        line: 'used / skipped / not_applicable，三种回执。',
        prevent: 'delivered 膨胀成 useful',
      },
      {
        name: '维护',
        en: 'Maintenance',
        line: 'Garden 四角色后台运行，只提案、永不直写。',
        prevent: '后台任务绕过闸门直写',
      },
    ],
  },
  gate: {
    title: '闸门迷你演示',
    sub: '候选记忆滑上传送带。这一次，闸门是你。',
    admit: '通过 Admit',
    reject: '驳回 Reject',
    auto: '自动 AUTO',
    manualNotice: '你现在是闸门',
    pool: '记忆池',
    durability: ['EventLog append', 'DB mutation', 'notify'],
    written: 'WRITTEN',
    rejected: 'REJECTED',
    statsProposed: '提议 proposed',
    statsWritten: '写入 written',
    statsRejected: '驳回 rejected',
    core: '“The agent proposes, the gate decides.”',
    coreZh: '「Agent 提议，闸门裁决。」',
    liveAdmit: '已通过，写入记忆池。',
    liveReject: '已驳回。',
    cards: [
      {
        key: 'A',
        claim: '「用户偏好 pnpm。」',
        arg: '论据：三次会话中观察一致 + 用户确认过',
        verdict: 'admit',
        reason: '',
      },
      {
        key: 'B',
        claim: '「应该用 mypy 严格模式。」',
        arg: '论据：agent said so',
        verdict: 'reject',
        reason: '「agent said so」不是治理论据',
      },
      {
        key: 'C',
        claim: '「上次那个 bug 是缓存引起的。」',
        arg: '论据：单次猜测，未复现',
        verdict: 'reject',
        reason: '证据不足',
      },
    ] as GateCard[],
  },
  recall: {
    kicker: '— 召回 RECALL, IN ORDER',
    title: '召回四策略',
    stages: ['粗筛 Coarse filter', 'FTS 全文检索', '精排 Rerank', 'embedding 仅加权补充'],
    never: '永不覆盖',
    note: '顺序固定。相似度只能加权，不能拍板。',
  },
  garden: {
    kicker: '— 维护 THE GARDENERS',
    title: 'Garden 四角色',
    roles: [
      { name: 'Auditor', zh: '审计员', duty: '核对 EventLog 与 DB 的一致性，发现分歧就提修复案。' },
      { name: 'Janitor', zh: '清道夫', duty: '清理过期与重复的候选记忆，只提删除案。' },
      { name: 'Librarian', zh: '编目员', duty: '维护索引与编目，提重排与归档案。' },
      { name: 'Scheduler', zh: '调度员', duty: '安排其余三位何时上岗，提调度案。' },
    ],
    line: '只提案，永不直写',
  },
  footnote: {
    kicker: '— 诚实声明 AN HONEST FOOTNOTE',
    line1: 'R@5 → 90% 尚未宣称达成 —— 500 条问题的大门还没跑完。',
    line2: '写在这里，是因为没做到的也该被记住。',
  },
  toolbox: {
    kicker: '— 工具箱 THE TOOLBOX',
    mcpTitle: '16 个 MCP 工具',
    mcpNote: 'soul.* ×13 + garden.* ×3',
    cliTitle: '13 个 CLI 动词',
    mcpTools: [
      'soul.remember',
      'soul.recall',
      'soul.resolve',
      'soul.receipt',
      'soul.propose',
      'soul.review',
      'soul.status',
      'soul.forget',
      'soul.link',
      'soul.audit',
      'soul.export',
      'soul.import',
      'soul.doctor',
      'garden.audit',
      'garden.propose',
      'garden.run',
    ],
    cliVerbs: [
      'remember',
      'recall',
      'resolve',
      'propose',
      'review',
      'receipt',
      'status',
      'forget',
      'link',
      'audit',
      'doctor',
      'export',
      'garden',
    ],
    zero: '零云默认：host_worker 模式，cloud edge-LLM 默认关闭。',
  },
  next: {
    title: '记忆有了。那它写中国字呢？',
    subtitle: '→ Write-Right',
  },
}

export type GateCard = {
  key: string
  claim: string
  arg: string
  verdict: 'admit' | 'reject'
  reason: string
}

export type AlayaContent = typeof zh

const en: AlayaContent = {
  hero: {
    kicker: '— 02 · MEMORY · DO-SOUL-ALAYA',
    title: 'Do-SOUL-Alaya',
    subtitle: 'The local-first memory plane for CLI coding agents',
    slogan: 'The local-first memory plane for CLI coding agents.',
    chips: ['v0.3.11', 'MIT', 'TypeScript', 'SQLite · WAL', 'MCP stdio', 'Node ≥20.19', 'pnpm ≥9'],
    ctaGithub: 'GitHub repo →',
    ctaDemo: 'Watch a memory live ↓',
    vertical: 'CLOSE THE TERMINAL, IT FORGETS',
  },
  itch: {
    kicker: '— THE ITCH',
    termPrompt: '$ exit',
    termC1: '# terminal closed',
    termC2: '# session over. it forgot everything.',
    big: "A vector DB answers 'what strings are similar' — not 'what is true'.",
    core: 'Similarity is not truth.',
  },
  grammar: {
    kicker: '— THE GRAMMAR · 3 LAYERS × 4 AXES',
    title: 'Three layers, four axes — one home each',
    layers: [
      { en: 'Memory Ontology', zh: '记忆本体' },
      { en: 'Structure Registry', zh: '结构注册' },
      { en: 'Runtime Control', zh: '运行时控制' },
    ],
    axes: [
      { en: 'Object', zh: '对象' },
      { en: 'Path', zh: '路径' },
      { en: 'Evidence', zh: '证据' },
      { en: 'Governance', zh: '治理' },
    ],
    cells: [
      [
        { label: 'Memory object', duty: 'Defines what one memory is.' },
        { label: 'Ontology path', duty: 'Identity and addressing of memories.' },
        { label: 'Provenance', duty: 'Evidence and provenance per memory.' },
        { label: 'State machine', duty: 'Candidate → live → rejected states.' },
      ],
      [
        { label: 'Structure objects', duty: 'Registry of hierarchies and relations.' },
        { label: 'Naming paths', duty: 'Naming paths and ownership of structures.' },
        { label: 'Change trail', duty: 'Audit trail of structure changes.' },
        { label: 'Structure proposals', duty: 'Changes by proposal, never direct writes.' },
      ],
      [
        { label: 'Runtime objects', duty: 'Sessions, signals, receipts.' },
        { label: 'Runtime paths', duty: 'Addressing the EventLog and queues.' },
        { label: 'Receipts', duty: 'Receipts and runtime metrics.' },
        { label: 'Gate rulings', duty: 'The six verdicts of soul.resolve.' },
      ],
    ],
    invariant: 'Invariant: any object, index, or state has exactly one axis as its source of truth.',
    hint: 'Tap a cell to see which axis it belongs to.',
  },
  lifecycle: {
    kicker: '— TRY IT · SIX STAGES, ONE GATE',
    title: 'The Lifecycle of a Memory',
    sub: 'A memory survives six stages. Click through, or let it flow.',
    auto: 'Auto-play',
    stageLabel: 'Stage',
    preventPrefix: 'prevents ✕',
    stages: [
      {
        name: 'Perception',
        en: '感知',
        line: 'Candidate signals enter and get routed — they never touch ontological truth.',
        prevent: 'the “fluent but wrong” becoming fact',
      },
      {
        name: 'Governance',
        en: '治理',
        line: 'Two review paths: inline soul.resolve (six verdicts), or out-of-band proposals.',
        prevent: '“agent said so” passing as a governance argument',
      },
      {
        name: 'Durability',
        en: '沉淀',
        line: 'EventLog append → DB mutation → notify. Audit before broadcast.',
        prevent: 'broadcast before audit',
      },
      {
        name: 'Recall',
        en: '召回',
        line: 'Coarse filter → FTS → rerank; embeddings only add weight, never override.',
        prevent: 'similarity outranking evidence',
      },
      {
        name: 'Receipt',
        en: '回执',
        line: 'used / skipped / not_applicable — three kinds of receipts.',
        prevent: 'delivered inflating into useful',
      },
      {
        name: 'Maintenance',
        en: '维护',
        line: 'Four Garden roles run in the background — they propose, never write.',
        prevent: 'background jobs bypassing the gate',
      },
    ],
  },
  gate: {
    title: 'The Gate Demo',
    sub: 'Candidate memories ride the conveyor. This time, you are the gate.',
    admit: 'Admit',
    reject: 'Reject',
    auto: 'AUTO',
    manualNotice: 'You are the gate now',
    pool: 'Memory pool',
    durability: ['EventLog append', 'DB mutation', 'notify'],
    written: 'WRITTEN',
    rejected: 'REJECTED',
    statsProposed: 'proposed',
    statsWritten: 'written',
    statsRejected: 'rejected',
    core: '“The agent proposes, the gate decides.”',
    coreZh: '「Agent 提议，闸门裁决。」',
    liveAdmit: 'Admitted and written to the pool.',
    liveReject: 'Rejected.',
    cards: [
      {
        key: 'A',
        claim: '“The user prefers pnpm.”',
        arg: 'Evidence: consistent across 3 sessions + confirmed by the user',
        verdict: 'admit',
        reason: '',
      },
      {
        key: 'B',
        claim: '“mypy strict mode should be on.”',
        arg: 'Evidence: agent said so',
        verdict: 'reject',
        reason: '"agent said so" is not a governance argument.',
      },
      {
        key: 'C',
        claim: '“That bug was caused by cache.”',
        arg: 'Evidence: a single guess, never reproduced',
        verdict: 'reject',
        reason: 'Insufficient evidence.',
      },
    ],
  },
  recall: {
    kicker: '— RECALL, IN ORDER',
    title: 'Recall, In Order',
    stages: ['Coarse filter', 'FTS full-text', 'Rerank', 'embedding (weight only)'],
    never: 'never overrides',
    note: 'Fixed order. Similarity may weigh in, never decide.',
  },
  garden: {
    kicker: '— THE GARDENERS',
    title: 'The Four Gardeners',
    roles: [
      { name: 'Auditor', zh: '审计员', duty: 'Cross-checks EventLog against the DB; files repair proposals on drift.' },
      { name: 'Janitor', zh: '清道夫', duty: 'Sweeps expired and duplicate candidates; files deletion proposals only.' },
      { name: 'Librarian', zh: '编目员', duty: 'Maintains indexes and the catalogue; files re-rank and archival proposals.' },
      { name: 'Scheduler', zh: '调度员', duty: 'Decides when the other three clock in; files scheduling proposals.' },
    ],
    line: 'proposes only, never writes.',
  },
  footnote: {
    kicker: '— AN HONEST FOOTNOTE',
    line1: "Recall@5 → 90% is NOT yet claimed. The 500-question gate hasn't been run.",
    line2: "Written here because what's undone deserves memory too.",
  },
  toolbox: {
    kicker: '— THE TOOLBOX',
    mcpTitle: '16 MCP tools',
    mcpNote: 'soul.* ×13 + garden.* ×3',
    cliTitle: '13 CLI verbs',
    mcpTools: [
      'soul.remember',
      'soul.recall',
      'soul.resolve',
      'soul.receipt',
      'soul.propose',
      'soul.review',
      'soul.status',
      'soul.forget',
      'soul.link',
      'soul.audit',
      'soul.export',
      'soul.import',
      'soul.doctor',
      'garden.audit',
      'garden.propose',
      'garden.run',
    ],
    cliVerbs: [
      'remember',
      'recall',
      'resolve',
      'propose',
      'review',
      'receipt',
      'status',
      'forget',
      'link',
      'audit',
      'doctor',
      'export',
      'garden',
    ],
    zero: 'Zero-cloud by default: host_worker mode; cloud edge-LLM off.',
  },
  next: {
    title: 'It remembers. But can it write formal Chinese?',
    subtitle: '→ Write-Right',
  },
}

export const alayaContent: Record<Lang, AlayaContent> = { zh, en }
