/**
 * do-it 项目页双语文案 · Bilingual copy for the do-it project page.
 * Owned by the do-it page agent — do NOT edit shared src/content.ts.
 */

const zh = {
  hero: {
    kicker: '— 壹 · 流程 PROCESS · DO-IT',
    title: 'do-it',
    subtitle: '可安装的 AI 编码工作流',
    slogan: 'Stop asking AI agents to remember process. Install it.',
    sloganAlt: '「别再让 AI 记住流程——直接把流程装进去。」',
    vertical: '把流程装进去',
    chips: ['v0.14.1', 'MIT', '⭐ 22', 'forks 2', 'Shell', 'CI ✓', 'CodeQL ✓'],
    hosts: ['Codex', 'Claude Code', 'Cursor', 'OpenCode', 'Kimi Code'],
    ctaRepo: 'GitHub 仓库 →',
    ctaTry: '试试下面的路由器 ↓',
    repoUrl: 'https://github.com/tdwhere123/do-it',
  },
  why: {
    kicker: '— 缘起 / WHY',
    itchTitle: '痛点 / The itch',
    itch: '每次都要把『怎么干活』重新讲一遍：先看哪、怎么测、什么叫做完。Agent 很聪明，但流程靠口口相传。',
    moveTitle: '做法 / The move',
    move: '把路由、委派、验证、复盘写成可安装的技能包。装进五个宿主，像装一个认真对待流程的同事。',
    note: '建议性路由，不是固定流水线 —— advisory, not a pipeline.',
  },
  sim: {
    kicker: '— 试试 / TRY IT · THE ROUTER',
    title: '随便描述一个任务，看它怎么被路由。',
    inputLabel: '描述一个任务',
    placeholder: '例如：给登录页加上验证码……',
    examples: [
      { id: 'ex-1', text: '改一下 README 里的错别字' },
      { id: 'ex-2', text: '给 API 增加分页和单元测试' },
      { id: 'ex-3', text: '把鉴权模块从 session 迁移到 JWT' },
      { id: 'ex-4', text: '重构整个状态管理并替换数据库 schema', failProve: true },
    ],
    routeButton: '路由一下',
    replay: '重播',
    actRoute: '幕 1 · ROUTE 路由',
    actDelegate: '幕 2 · DELEGATE 委派',
    actProve: '幕 3 · PROVE 验证',
    levels: ['LIGHT', 'STANDARD', 'HEAVY'] as const,
    levelZh: { LIGHT: '轻量', STANDARD: '标准', HEAVY: '重工' },
    signalsPrefix: '命中信号：',
    signalsNone: '（无关键词）',
    unclear: '没看清，先按标准件处理。',
    bucketsLabel: '推荐 buckets',
    delegateNote: '可选专家，按需上桌 —— optional specialists, seated as needed.',
    proveItems: [
      '测试是刚跑的、绿的新鲜证据',
      '改动与声明一一对应',
      '没有顺手带进来的无关改动',
    ],
    verified: 'VERIFIED',
    notVerified: 'NOT_VERIFIED',
    notVerifiedNote: '「done」是证据声明，不是心情。',
    learnLabel: '幕 4 · 行为学习 LEARN',
    learnState: '默认关闭',
    learnTip: '默认关闭。本地脱敏记录，/do-it-retrospective 才生成报告。',
    idleHint: '输入任务，或点一个示例，看它怎么被路由。',
    summaryPrefix: '路由结果',
  },
  moves: {
    kicker: '— 四步功法 / THE FOUR MOVES',
    items: [
      {
        en: 'Route the work',
        zh: '路由任务',
        desc: '每个 prompt 先定风险级，再决定加载哪些 meaning buckets。',
      },
      {
        en: 'Delegate freely',
        zh: '自由委派',
        desc: '十个可选子代理专家，按需上桌，不是固定流水线。',
      },
      {
        en: 'Prove the result',
        zh: '证明结果',
        desc: '「done」必须附新鲜证据，否则 NOT_VERIFIED。',
      },
      {
        en: 'Learn from behavior',
        zh: '行为学习',
        desc: '本地脱敏记录，回顾报告只在你要看时生成。',
      },
    ],
    learnBadge: '默认关闭 / off by default',
  },
  ladder: {
    kicker: '— 决策阶梯 / KEEP IT SMALL',
    title: '安全第一，能小则小。',
    steps: [
      '这东西需要存在吗？',
      '标准库能解决吗？',
      '平台原生支持吗？',
      '一个成熟依赖？',
      '一行代码？',
      '最小自研',
    ],
  },
  specs: {
    kicker: '— 规格与致谢 / SPECS & CREDITS',
    bucketsTitle: '技能桶 / Buckets',
    buckets: ['do-it-router', 'do-it-code-quality', 'do-it-decide', 'do-it-review', 'do-it-verify'],
    extensions: '4 个扩展',
    creditsTitle: '站在肩上 / Standing on shoulders',
    credits: ['obra/superpowers', 'mattpocock/skills', 'addyosmani/agent-skills', 'DietrichGebert/ponytail'],
    creditsNote: '以及 Linux.do 社区的各位。',
  },
  next: {
    title: '流程有了。那它的记忆呢？',
    subtitle: 'Do-SOUL-Alaya · 记忆之屋',
  },
}

export type DoItContent = typeof zh

const en: DoItContent = {
  hero: {
    kicker: '— 01 · PROCESS · DO-IT',
    title: 'do-it',
    subtitle: 'An installable workflow for AI coding agents',
    slogan: 'Stop asking AI agents to remember process. Install it.',
    sloganAlt: '"Process, installed — not memorized."',
    vertical: '把流程装进去',
    chips: ['v0.14.1', 'MIT', '⭐ 22', 'forks 2', 'Shell', 'CI ✓', 'CodeQL ✓'],
    hosts: ['Codex', 'Claude Code', 'Cursor', 'OpenCode', 'Kimi Code'],
    ctaRepo: 'GitHub repo →',
    ctaTry: 'Try the router below ↓',
    repoUrl: 'https://github.com/tdwhere123/do-it',
  },
  why: {
    kicker: '— WHY / THE ITCH',
    itchTitle: 'The itch / 痛点',
    itch: "Every session, you re-teach how work gets done — what to read first, how to test, what 'done' means. Smart agent, folklore process.",
    moveTitle: 'The move / 做法',
    move: 'Route, delegate, verify, retrospect — written as installable skills. Five hosts, one disciplined colleague.',
    note: 'Advisory routing, not a fixed pipeline — 建议性路由，不是固定流水线。',
  },
  sim: {
    kicker: '— TRY IT · THE ROUTER',
    title: 'Describe any task. Watch it get routed.',
    inputLabel: 'Describe a task',
    placeholder: 'e.g. add captcha to the login page…',
    examples: [
      { id: 'ex-1', text: 'fix a typo in the README' },
      { id: 'ex-2', text: 'add pagination and unit tests to the API' },
      { id: 'ex-3', text: 'migrate the auth module from session to JWT' },
      { id: 'ex-4', text: 'refactor all state management and replace the DB schema', failProve: true },
    ],
    routeButton: 'Route it',
    replay: 'Replay',
    actRoute: 'Act 1 · ROUTE',
    actDelegate: 'Act 2 · DELEGATE',
    actProve: 'Act 3 · PROVE',
    levels: ['LIGHT', 'STANDARD', 'HEAVY'] as const,
    levelZh: { LIGHT: 'light', STANDARD: 'standard', HEAVY: 'heavy' },
    signalsPrefix: 'Signals hit: ',
    signalsNone: '(no keywords)',
    unclear: 'Unclear — defaulting to Standard.',
    bucketsLabel: 'Recommended buckets',
    delegateNote: 'Optional specialists, seated as needed — 可选专家，按需上桌。',
    proveItems: [
      'fresh green test run, not vibes',
      'diff matches the claim',
      'no hitchhiker changes',
    ],
    verified: 'VERIFIED',
    notVerified: 'NOT_VERIFIED',
    notVerifiedNote: '"done" is a claim of evidence, not a mood.',
    learnLabel: 'Act 4 · LEARN from behavior',
    learnState: 'off by default',
    learnTip: 'Off by default. Local, sanitized; /do-it-retrospective reports.',
    idleHint: 'Type a task, or tap an example, and watch it get routed.',
    summaryPrefix: 'Routed',
  },
  moves: {
    kicker: '— THE FOUR MOVES / 四步功法',
    items: [
      {
        en: 'Route the work',
        zh: '路由任务',
        desc: 'Every prompt gets a risk grade first — that grade picks the meaning buckets to load.',
      },
      {
        en: 'Delegate freely',
        zh: '自由委派',
        desc: 'Ten optional specialist sub-agents, seated as needed. Not a fixed pipeline.',
      },
      {
        en: 'Prove the result',
        zh: '证明结果',
        desc: '"done" must ship fresh evidence, or it comes back NOT_VERIFIED.',
      },
      {
        en: 'Learn from behavior',
        zh: '行为学习',
        desc: 'Local, sanitized records. The retrospective report exists only when you ask.',
      },
    ],
    learnBadge: 'off by default / 默认关闭',
  },
  ladder: {
    kicker: '— KEEP IT SMALL / 决策阶梯',
    title: 'Safety first, smallest thing that works.',
    steps: [
      'Does it need to exist?',
      'Can the stdlib solve it?',
      'Is it platform-native?',
      'One solid dependency?',
      'One line of code?',
      'Smallest custom build',
    ],
  },
  specs: {
    kicker: '— SPECS & CREDITS / 规格与致谢',
    bucketsTitle: 'Buckets / 技能桶',
    buckets: ['do-it-router', 'do-it-code-quality', 'do-it-decide', 'do-it-review', 'do-it-verify'],
    extensions: '4 extensions',
    creditsTitle: 'Standing on shoulders / 站在肩上',
    credits: ['obra/superpowers', 'mattpocock/skills', 'addyosmani/agent-skills', 'DietrichGebert/ponytail'],
    creditsNote: 'and the Linux.do community.',
  },
  next: {
    title: 'Process, installed. But what does it remember?',
    subtitle: 'Do-SOUL-Alaya · the memory room',
  },
}

export const doItContent: { zh: DoItContent; en: DoItContent } = { zh, en }
