/**
 * Write-Right 项目页双语文案 · Bilingual copy for the Write-Right project page.
 * Owned by the Write-Right page agent — do NOT edit shared src/content.ts.
 */

const zh = {
  hero: {
    kicker: '— 叁 · 写作 WRITING · WRITE-RIGHT',
    title: 'Write-Right',
    subtitle: '模型无关的中文正式写作 Agent Skills 包',
    slogan: '「文种 × 场所 × 目标，路由先于动笔。」',
    vertical: '路由先于动笔',
    stamp: '施工中 · 2026-07 起步',
    chips: ['进行中 WIP', 'Python', '纯开源 · 无宿主 App', '本地优先'],
    hosts: ['Claude Code', 'Codex', 'WorkBuddy（CodeBuddy）'],
    ctaRepo: 'GitHub 仓库 →',
    ctaTry: '试试文种路由 ↓',
    repoUrl: 'https://github.com/tdwhere123/write-right',
  },
  scope: {
    kicker: '— 做与不做 / SCOPE, HONESTLY',
    doesTitle: '做 / DOES',
    doesntTitle: '不做 / DOESN’T',
    does: [
      '文种×场所×目标路由',
      '选择式框架与段落',
      '任务内 resume 工人',
      '本地 writing-desk 偏好学习（staging→active）',
      '项目素材召回',
      '白名单按需联网落盘',
    ],
    doesnt: ['红头排版主路径', '绑死单一模型', '云端记忆'],
    note: '边界写清楚，比功能写得多更重要。',
  },
  plate: {
    kicker: '— 展品 / THE DESK',
    alt: '写作案头：毛笔与印章旁摊开文种路由笺，墨迹未干',
    caption: '路由先于动笔。案头只留骨架与场所——空白页不是起点，选格才是。',
  },
  router: {
    kicker: '— 试试 / TRY IT · ROUTE BEFORE YOU WRITE',
    title: '选三个格子，看它给你一副骨架。',
    genreLabel: '文种 Genre',
    settingLabel: '场所 Setting',
    goalLabel: '目标 Goal',
    genres: [
      { id: 'qingshi', label: '请示' },
      { id: 'baogao', label: '报告' },
      { id: 'tongzhi', label: '通知' },
      { id: 'han', label: '函' },
      { id: 'jianghua', label: '讲话稿' },
      { id: 'zongjie', label: '工作总结' },
    ],
    settings: [
      { id: 'up', label: '上行 · 对上级' },
      { id: 'parallel', label: '平行 · 对平级' },
      { id: 'down', label: '下行 · 对下级' },
    ],
    goals: [
      { id: 'support', label: '争取支持' },
      { id: 'progress', label: '汇报进展' },
      { id: 'deploy', label: '部署工作' },
      { id: 'discuss', label: '商洽事项' },
    ],
    tones: {
      up: '语气：请示语气，一文一事',
      parallel: '语气：平等商洽',
      down: '语气：明确、可执行',
    },
    highlightNote: '这里是重点',
    skeletons: {
      qingshi: [
        { label: '标题', hint: '关于……的请示' },
        { label: '主送机关', hint: '一文一主送，不多头' },
        { label: '缘由', hint: '一句话说清背景，不诉苦' },
        { label: '事项', hint: '请什么，具体到可批复' },
        { label: '结语', hint: '「妥否，请批示。」' },
        { label: '落款', hint: '单位与日期' },
      ],
      baogao: [
        { label: '标题', hint: '关于……的报告' },
        { label: '主送机关', hint: '' },
        { label: '基本情况', hint: '全景两句，不展开' },
        { label: '主要做法 / 进展', hint: '分条，讲数据' },
        { label: '存在问题', hint: '写真问题' },
        { label: '下一步打算', hint: '可检查的动作' },
        { label: '落款', hint: '' },
      ],
      tongzhi: [
        { label: '标题', hint: '' },
        { label: '主送机关', hint: '' },
        { label: '依据 / 目的', hint: '根据……，为了……' },
        { label: '事项', hint: '时间 / 地点 / 要求' },
        { label: '执行要求', hint: '谁、什么时候、做到什么' },
        { label: '落款', hint: '' },
      ],
      han: [
        { label: '标题', hint: '' },
        { label: '主送机关', hint: '' },
        { label: '缘由', hint: '为什么写这封信' },
        { label: '商洽 / 告知事项', hint: '一事一函' },
        { label: '结语', hint: '「特此函达。」' },
        { label: '落款', hint: '' },
      ],
      jianghua: [
        { label: '称谓', hint: '各位……：' },
        { label: '开场', hint: '场合与谢意' },
        { label: '主体', hint: '三点式，一点一例子' },
        { label: '结尾', hint: '号召 / 祝愿' },
      ],
      zongjie: [
        { label: '标题', hint: '' },
        { label: '总体评价', hint: '一句话定调' },
        { label: '成绩与经验', hint: '成绩写够，经验写透' },
        { label: '问题与教训', hint: '不回避' },
        { label: '下一步安排', hint: '' },
      ],
    } as Record<string, { label: string; hint: string }[]>,
    /** per genre, per goal: index of the skeleton item that becomes the focus */
    goalFocus: {
      qingshi: { support: 3, progress: 2, deploy: 3, discuss: 3 },
      baogao: { support: 3, progress: 3, deploy: 5, discuss: 4 },
      tongzhi: { support: 3, progress: 4, deploy: 4, discuss: 3 },
      han: { support: 3, progress: 3, deploy: 3, discuss: 3 },
      jianghua: { support: 2, progress: 2, deploy: 2, discuss: 2 },
      zongjie: { support: 2, progress: 2, deploy: 4, discuss: 3 },
    } as Record<string, Record<string, number>>,
    footerNote: '这是骨架，不是代笔。动笔的还是你。',
  },
  repo: {
    kicker: '— 仓库形状 / THE SHAPE OF THE REPO',
    title: '一棵树，core 是唯一真源。',
    nodes: [
      {
        id: 'core',
        label: 'core/',
        tag: '唯一真源',
        children: ['skills/', 'references/', 'capability-matrix'],
        note: '只在这里改。adapters 只是投影。',
      },
      {
        id: 'adapters',
        label: 'adapters/',
        tag: '三宿主薄投影',
        children: [],
        note: '三个宿主的薄投影，从 core 同步生成，不手改。',
      },
      {
        id: 'writing-desk',
        label: 'writing-desk/',
        tag: '本地记忆（偏好 staging→active）',
        children: [],
        note: '你的偏好，本地学，staging 验过才进 active。',
      },
      {
        id: 'vault',
        label: 'vault/',
        tag: '范文 / 素材 / web 落盘',
        children: [],
        note: '素材落盘才可信。',
      },
      {
        id: 'tools',
        label: 'tools/',
        tag: 'sync_* + wr_desk / vault / task / recall / ingest',
        children: [],
        note: 'sync_* 与五个 wr_* 动词的家。',
      },
      {
        id: 'evals',
        label: 'evals/  docs/',
        tag: '',
        children: [],
        note: '评测与文档。骨架要经得起测。',
      },
    ],
  },
  daily: {
    kicker: '— 日常路径 / THE DAILY PATH',
    title: '五个动词。',
    loopLabel: '回到 wr_task · 闭环',
    steps: [
      { cmd: 'wr_task', note: '选择闭环', example: 'wr_task new --genre 请示' },
      { cmd: 'wr_desk', note: '偏好学习', example: 'wr_desk promote --from staging' },
      { cmd: 'wr_vault', note: '素材入库', example: 'wr_vault add ./范文/讲话稿.md' },
      { cmd: 'wr_recall', note: '项目召回', example: 'wr_recall --project 旧城改造' },
      { cmd: 'wr_ingest', note: '白名单联网落盘', example: 'wr_ingest https://allowed.example/policy' },
    ],
  },
  privacy: {
    kicker: '— 隐私与边界 / PRIVACY',
    lines: [
      'writing-desk 与 vault 默认不提交、不上传。',
      '联网只走白名单，落盘才算数。',
    ],
  },
  next: {
    title: '大项目逛完了。院角有一处遗址和一只抽屉',
    subtitle: 'playground · SENTINEL 遗址与素菜卡片',
  },
}

export type WriteRightContent = typeof zh

const en: WriteRightContent = {
  hero: {
    kicker: '— 03 · WRITING · WRITE-RIGHT',
    title: 'Write-Right',
    subtitle: 'A model-agnostic Agent Skills pack for formal Chinese writing',
    slogan: '"Genre × setting × goal — route before you write."',
    vertical: '路由先于动笔',
    stamp: 'WIP · started 2026-07',
    chips: ['WIP', 'Python', 'open source · no host app', 'local-first'],
    hosts: ['Claude Code', 'Codex', 'WorkBuddy（CodeBuddy）'],
    ctaRepo: 'GitHub repo →',
    ctaTry: 'Try the genre router ↓',
    repoUrl: 'https://github.com/tdwhere123/write-right',
  },
  scope: {
    kicker: '— SCOPE, HONESTLY / 做与不做',
    doesTitle: 'DOES / 做',
    doesntTitle: 'DOESN’T / 不做',
    does: [
      'genre × setting × goal routing',
      'choose-your-own skeletons & paragraphs',
      'in-task resume workers',
      'local writing-desk preference learning (staging→active)',
      'project material recall',
      'whitelist-only web fetch, straight to disk',
    ],
    doesnt: ['red-header typesetting as the main path', 'hard-bound to a single model', 'cloud memory'],
    note: 'Honest edges beat long feature lists.',
  },
  plate: {
    kicker: '— THE DESK / 展品',
    alt: 'A writing desk: genre-routing slips beside brush and seal, ink still wet',
    caption:
      'Route before you write. The desk holds a skeleton and a setting — the blank page is not the start; the three grids are.',
  },
  router: {
    kicker: '— TRY IT · ROUTE BEFORE YOU WRITE',
    title: 'Pick three. Get a skeleton, not a blank page.',
    genreLabel: 'Genre · 文种',
    settingLabel: 'Setting · 场所',
    goalLabel: 'Goal · 目标',
    genres: [
      { id: 'qingshi', label: 'Request 请示' },
      { id: 'baogao', label: 'Report 报告' },
      { id: 'tongzhi', label: 'Notice 通知' },
      { id: 'han', label: 'Letter 函' },
      { id: 'jianghua', label: 'Speech 讲话稿' },
      { id: 'zongjie', label: 'Summary 工作总结' },
    ],
    settings: [
      { id: 'up', label: 'Upward · to superiors' },
      { id: 'parallel', label: 'Parallel · to peers' },
      { id: 'down', label: 'Downward · to reports' },
    ],
    goals: [
      { id: 'support', label: 'Win support' },
      { id: 'progress', label: 'Report progress' },
      { id: 'deploy', label: 'Deploy work' },
      { id: 'discuss', label: 'Discuss matters' },
    ],
    tones: {
      up: 'Tone: petitioning — one matter per document',
      parallel: 'Tone: equal footing, consultative',
      down: 'Tone: explicit, actionable',
    },
    highlightNote: 'the ask lives here',
    skeletons: {
      qingshi: [
        { label: 'Title', hint: '"Regarding …: a request"' },
        { label: 'Addressed body', hint: 'one recipient, no multi-addressing' },
        { label: 'Rationale', hint: 'background in one sentence, no grievances' },
        { label: 'The ask', hint: 'specific enough to approve' },
        { label: 'Closing', hint: '"Is this acceptable? Please advise." (妥否，请批示。)' },
        { label: 'Signature', hint: 'org and date' },
      ],
      baogao: [
        { label: 'Title', hint: '"Report on …"' },
        { label: 'Addressed body', hint: '' },
        { label: 'Situation overview', hint: 'the whole picture in two sentences' },
        { label: 'Approach / progress', hint: 'itemized, with numbers' },
        { label: 'Outstanding problems', hint: 'the real ones' },
        { label: 'Next steps', hint: 'checkable actions' },
        { label: 'Signature', hint: '' },
      ],
      tongzhi: [
        { label: 'Title', hint: '' },
        { label: 'Addressed bodies', hint: '' },
        { label: 'Basis / purpose', hint: '"Per …, in order to …"' },
        { label: 'Particulars', hint: 'time / place / requirements' },
        { label: 'Execution requirements', hint: 'who, by when, to what standard' },
        { label: 'Signature', hint: '' },
      ],
      han: [
        { label: 'Title', hint: '' },
        { label: 'Addressed body', hint: '' },
        { label: 'Rationale', hint: 'why this letter exists' },
        { label: 'Matter for discussion / notice', hint: 'one matter per letter' },
        { label: 'Closing', hint: '"Hereby conveyed." (特此函达。)' },
        { label: 'Signature', hint: '' },
      ],
      jianghua: [
        { label: 'Salutation', hint: '"Dear …,"' },
        { label: 'Opening', hint: 'occasion and thanks' },
        { label: 'Body', hint: 'three points, each with one example' },
        { label: 'Close', hint: 'call to action / good wishes' },
      ],
      zongjie: [
        { label: 'Title', hint: '' },
        { label: 'Overall assessment', hint: 'one sentence sets the tone' },
        { label: 'Results & lessons', hint: 'results in full, lessons in depth' },
        { label: 'Problems & mistakes', hint: 'unflinching' },
        { label: 'Next steps', hint: '' },
      ],
    } as Record<string, { label: string; hint: string }[]>,
    goalFocus: {
      qingshi: { support: 3, progress: 2, deploy: 3, discuss: 3 },
      baogao: { support: 3, progress: 3, deploy: 5, discuss: 4 },
      tongzhi: { support: 3, progress: 4, deploy: 4, discuss: 3 },
      han: { support: 3, progress: 3, deploy: 3, discuss: 3 },
      jianghua: { support: 2, progress: 2, deploy: 2, discuss: 2 },
      zongjie: { support: 2, progress: 2, deploy: 4, discuss: 3 },
    } as Record<string, Record<string, number>>,
    footerNote: 'A skeleton, not a ghost-writer. The pen stays yours.',
  },
  repo: {
    kicker: '— THE SHAPE OF THE REPO / 仓库形状',
    title: 'One tree. core is the single source of truth.',
    nodes: [
      {
        id: 'core',
        label: 'core/',
        tag: 'single source of truth',
        children: ['skills/', 'references/', 'capability-matrix'],
        note: 'Edit here only; adapters are projections.',
      },
      {
        id: 'adapters',
        label: 'adapters/',
        tag: 'thin projections for 3 hosts',
        children: [],
        note: 'Thin projections for the three hosts — synced from core, never hand-edited.',
      },
      {
        id: 'writing-desk',
        label: 'writing-desk/',
        tag: 'local memory (preferences staging→active)',
        children: [],
        note: 'Learns your taste locally; staging before active.',
      },
      {
        id: 'vault',
        label: 'vault/',
        tag: 'exemplars / material / web-to-disk',
        children: [],
        note: "Only what's on disk is trustworthy.",
      },
      {
        id: 'tools',
        label: 'tools/',
        tag: 'sync_* + wr_desk / vault / task / recall / ingest',
        children: [],
        note: 'Home of sync_* and the five wr_* verbs.',
      },
      {
        id: 'evals',
        label: 'evals/  docs/',
        tag: '',
        children: [],
        note: 'Evals and docs — skeletons must survive testing.',
      },
    ],
  },
  daily: {
    kicker: '— THE DAILY PATH / 日常路径',
    title: 'Five verbs.',
    loopLabel: 'back to wr_task · the loop',
    steps: [
      { cmd: 'wr_task', note: 'close the loop', example: 'wr_task new --genre 请示' },
      { cmd: 'wr_desk', note: 'learn preferences', example: 'wr_desk promote --from staging' },
      { cmd: 'wr_vault', note: 'shelve material', example: 'wr_vault add ./exemplars/speech.md' },
      { cmd: 'wr_recall', note: 'recall project context', example: 'wr_recall --project old-town' },
      { cmd: 'wr_ingest', note: 'whitelisted web → disk', example: 'wr_ingest https://allowed.example/policy' },
    ],
  },
  privacy: {
    kicker: '— PRIVACY / 隐私与边界',
    lines: [
      'Your desk and vault are never committed, never uploaded.',
      "Network access is whitelist-only; nothing counts until it's on disk.",
    ],
  },
  next: {
    title: "That's the three rooms. Now — a ruin and a drawer in the corner",
    subtitle: 'playground · the SENTINEL ruin and the recipe drawer',
  },
}

export const writeRightContent: { zh: WriteRightContent; en: WriteRightContent } = { zh, en }
